-- Create industries table
CREATE TABLE public.industries (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create index for better search performance
CREATE INDEX idx_industries_name ON public.industries(name);
CREATE INDEX idx_industries_slug ON public.industries(slug);

-- Add trigger to update updated_at column
CREATE TRIGGER update_industries_updated_at
  BEFORE UPDATE ON public.industries
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Insert all industries
INSERT INTO public.industries (name, slug) VALUES
  ('Accounting', 'accounting'),
  ('Airlines/Aviation', 'airlines-aviation'),
  ('Alternative Dispute Resolution', 'alternative-dispute-resolution'),
  ('Alternative Medicine', 'alternative-medicine'),
  ('Animation', 'animation'),
  ('Apparel & Fashion', 'apparel-fashion'),
  ('Architecture & Planning', 'architecture-planning'),
  ('Arts & Crafts', 'arts-crafts'),
  ('Automotive', 'automotive'),
  ('Aviation & Aerospace', 'aviation-aerospace'),
  ('Banking', 'banking'),
  ('Biotechnology', 'biotechnology'),
  ('Broadcast Media', 'broadcast-media'),
  ('Building Materials', 'building-materials'),
  ('Business Supplies & Equipment', 'business-supplies-equipment'),
  ('Capital Markets', 'capital-markets'),
  ('Chemicals', 'chemicals'),
  ('Civic & Social Organization', 'civic-social-organization'),
  ('Civil Engineering', 'civil-engineering'),
  ('Commercial Real Estate', 'commercial-real-estate'),
  ('Computer & Network Security', 'computer-network-security'),
  ('Computer Games', 'computer-games'),
  ('Computer Hardware', 'computer-hardware'),
  ('Computer Networking', 'computer-networking'),
  ('Computer Software', 'computer-software'),
  ('Construction', 'construction'),
  ('Consumer Electronics', 'consumer-electronics'),
  ('Consumer Goods', 'consumer-goods'),
  ('Consumer Services', 'consumer-services'),
  ('Cosmetics', 'cosmetics'),
  ('Dairy', 'dairy'),
  ('Defense & Space', 'defense-space'),
  ('Design', 'design'),
  ('Education Management', 'education-management'),
  ('E-learning', 'e-learning'),
  ('Electrical & Electronic Manufacturing', 'electrical-electronic-manufacturing'),
  ('Entertainment', 'entertainment'),
  ('Environmental Services', 'environmental-services'),
  ('Events Services', 'events-services'),
  ('Executive Office', 'executive-office'),
  ('Facilities Services', 'facilities-services'),
  ('Farming', 'farming'),
  ('Financial Services', 'financial-services'),
  ('Fine Art', 'fine-art'),
  ('Fishery', 'fishery'),
  ('Food & Beverages', 'food-beverages'),
  ('Food Production', 'food-production'),
  ('Fundraising', 'fundraising'),
  ('Furniture', 'furniture'),
  ('Gambling & Casinos', 'gambling-casinos'),
  ('Glass, Ceramics & Concrete', 'glass-ceramics-concrete'),
  ('Government Administration', 'government-administration'),
  ('Government Relations', 'government-relations'),
  ('Graphic Design', 'graphic-design'),
  ('Health, Wellness & Fitness', 'health-wellness-fitness'),
  ('Higher Education', 'higher-education'),
  ('Hospital & Health Care', 'hospital-health-care'),
  ('Hospitality', 'hospitality'),
  ('Human Resources', 'human-resources'),
  ('Import & Export', 'import-export'),
  ('Individual & Family Services', 'individual-family-services'),
  ('Industrial Automation', 'industrial-automation'),
  ('Information Services', 'information-services'),
  ('Information Technology & Services', 'information-technology-services'),
  ('Insurance', 'insurance'),
  ('International Affairs', 'international-affairs'),
  ('International Trade & Development', 'international-trade-development'),
  ('Internet', 'internet'),
  ('Investment Banking/Venture', 'investment-banking-venture'),
  ('Investment Management', 'investment-management'),
  ('Judiciary', 'judiciary'),
  ('Law Enforcement', 'law-enforcement'),
  ('Law Practice', 'law-practice'),
  ('Legal Services', 'legal-services'),
  ('Legislative Office', 'legislative-office'),
  ('Leisure & Travel', 'leisure-travel'),
  ('Libraries', 'libraries'),
  ('Logistics & Supply Chain', 'logistics-supply-chain'),
  ('Luxury Goods & Jewelry', 'luxury-goods-jewelry'),
  ('Machinery', 'machinery'),
  ('Management Consulting', 'management-consulting'),
  ('Maritime', 'maritime'),
  ('Marketing & Advertising', 'marketing-advertising'),
  ('Market Research', 'market-research'),
  ('Mechanical or Industrial Engineering', 'mechanical-industrial-engineering'),
  ('Media Production', 'media-production'),
  ('Medical Device', 'medical-device'),
  ('Medical Practice', 'medical-practice'),
  ('Mental Health Care', 'mental-health-care'),
  ('Military', 'military'),
  ('Mining & Metals', 'mining-metals'),
  ('Motion Pictures & Film', 'motion-pictures-film'),
  ('Museums & Institutions', 'museums-institutions'),
  ('Music', 'music'),
  ('Nanotechnology', 'nanotechnology'),
  ('Newspapers', 'newspapers'),
  ('Nonprofit Organization Management', 'nonprofit-organization-management'),
  ('Oil & Energy', 'oil-energy'),
  ('Online Publishing', 'online-publishing'),
  ('Outsourcing/Offshoring', 'outsourcing-offshoring'),
  ('Package/Freight Delivery', 'package-freight-delivery'),
  ('Packaging & Containers', 'packaging-containers'),
  ('Paper & Forest Products', 'paper-forest-products'),
  ('Performing Arts', 'performing-arts'),
  ('Pharmaceuticals', 'pharmaceuticals'),
  ('Philanthropy', 'philanthropy'),
  ('Photography', 'photography'),
  ('Plastics', 'plastics'),
  ('Political Organization', 'political-organization'),
  ('Primary/Secondary', 'primary-secondary'),
  ('Printing', 'printing'),
  ('Professional Training', 'professional-training'),
  ('Program Development', 'program-development'),
  ('Public Policy', 'public-policy'),
  ('Public Relations', 'public-relations'),
  ('Public Safety', 'public-safety'),
  ('Publishing', 'publishing'),
  ('Railroad Manufacture', 'railroad-manufacture'),
  ('Ranching', 'ranching'),
  ('Real Estate', 'real-estate'),
  ('Recreational', 'recreational'),
  ('Facilities & Services', 'facilities-services-recreational'),
  ('Religious Institutions', 'religious-institutions'),
  ('Renewables & Environment', 'renewables-environment'),
  ('Research', 'research'),
  ('Restaurants', 'restaurants'),
  ('Retail', 'retail'),
  ('Security & Investigations', 'security-investigations'),
  ('Semiconductors', 'semiconductors'),
  ('Shipbuilding', 'shipbuilding'),
  ('Sporting Goods', 'sporting-goods'),
  ('Sports', 'sports'),
  ('Staffing & Recruiting', 'staffing-recruiting'),
  ('Supermarkets', 'supermarkets'),
  ('Telecommunications', 'telecommunications'),
  ('Textiles', 'textiles'),
  ('Think Tanks', 'think-tanks'),
  ('Tobacco', 'tobacco'),
  ('Translation & Localization', 'translation-localization'),
  ('Transportation/Trucking/Railroad', 'transportation-trucking-railroad'),
  ('Utilities', 'utilities'),
  ('Venture Capital', 'venture-capital'),
  ('Veterinary', 'veterinary'),
  ('Warehousing', 'warehousing'),
  ('Wholesale', 'wholesale'),
  ('Wine & Spirits', 'wine-spirits'),
  ('Wireless', 'wireless'),
  ('Writing & Editing', 'writing-editing');
