
-- Create timezones table with comprehensive timezone data
CREATE TABLE timezones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    value TEXT UNIQUE NOT NULL,
    abbr TEXT NOT NULL,
    utc_offset NUMERIC NOT NULL,
    isdst BOOLEAN NOT NULL,
    text TEXT NOT NULL,
    utc TEXT[] NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Create indexes for efficient querying
CREATE INDEX idx_timezones_value ON timezones(value);
CREATE INDEX idx_timezones_abbr ON timezones(abbr);
CREATE INDEX idx_timezones_utc_offset ON timezones(utc_offset);
CREATE INDEX idx_timezones_text ON timezones(text);

-- Insert timezone data
INSERT INTO timezones (value, abbr, utc_offset, isdst, text, utc) VALUES
('Dateline Standard Time', 'DST', -12, false, '(UTC-12:00) International Date Line West', ARRAY['Etc/GMT+12']),
('UTC-11', 'U', -11, false, '(UTC-11:00) Coordinated Universal Time-11', ARRAY['Etc/GMT+11', 'Pacific/Midway', 'Pacific/Niue', 'Pacific/Pago_Pago']),
('Aleutian Standard Time', 'HAST', -10, false, '(UTC-10:00) Aleutian Islands', ARRAY['America/Adak']),
('Hawaiian Standard Time', 'HST', -10, false, '(UTC-10:00) Hawaii', ARRAY['Etc/GMT+10', 'Pacific/Honolulu', 'Pacific/Johnston', 'Pacific/Rarotonga', 'Pacific/Tahiti']),
('Marquesas Standard Time', 'MST', -9.5, false, '(UTC-09:30) Marquesas Islands', ARRAY['Pacific/Marquesas']),
('Alaskan Standard Time', 'AKST', -9, false, '(UTC-09:00) Alaska', ARRAY['America/Anchorage', 'America/Juneau', 'America/Metlakatla', 'America/Nome', 'America/Sitka', 'America/Yakutat']),
('UTC-09', 'U', -9, false, '(UTC-09:00) Coordinated Universal Time-09', ARRAY['Etc/GMT+9', 'Pacific/Gambier']),
('Pacific Standard Time (Mexico)', 'PST', -8, false, '(UTC-08:00) Baja California', ARRAY['America/Tijuana']),
('UTC-08', 'U', -8, false, '(UTC-08:00) Coordinated Universal Time-08', ARRAY['Etc/GMT+8', 'Pacific/Pitcairn']),
('Pacific Standard Time', 'PST', -8, false, '(UTC-08:00) Pacific Time (US & Canada)', ARRAY['America/Los_Angeles', 'America/Vancouver']),
('US Mountain Standard Time', 'MST', -7, false, '(UTC-07:00) Arizona', ARRAY['America/Creston', 'America/Dawson_Creek', 'America/Fort_Nelson', 'America/Phoenix']),
('Mountain Standard Time (Mexico)', 'MST', -7, false, '(UTC-07:00) Chihuahua, La Paz, Mazatlan', ARRAY['America/Chihuahua', 'America/Mazatlan']),
('Mountain Standard Time', 'MST', -7, false, '(UTC-07:00) Mountain Time (US & Canada)', ARRAY['America/Denver', 'America/Edmonton']),
('Central America Standard Time', 'CST', -6, false, '(UTC-06:00) Central America', ARRAY['America/Belize', 'America/Costa_Rica', 'America/El_Salvador', 'America/Guatemala', 'America/Managua', 'America/Tegucigalpa', 'Etc/GMT+6', 'Pacific/Galapagos']),
('Central Standard Time', 'CST', -6, false, '(UTC-06:00) Central Time (US & Canada)', ARRAY['America/Chicago', 'America/Winnipeg']),
('Easter Island Standard Time', 'EIST', -6, false, '(UTC-06:00) Easter Island', ARRAY['Pacific/Easter']),
('Central Standard Time (Mexico)', 'CST', -6, false, '(UTC-06:00) Guadalajara, Mexico City, Monterrey', ARRAY['America/Mexico_City']),
('Canada Central Standard Time', 'CST', -6, false, '(UTC-06:00) Saskatchewan', ARRAY['America/Regina']),
('SA Pacific Standard Time', 'SPT', -5, false, '(UTC-05:00) Bogota, Lima, Quito, Rio Branco', ARRAY['America/Bogota', 'America/Cayman', 'America/Coral_Harbour', 'America/Eirunepe', 'America/Guayaquil', 'America/Jamaica', 'America/Lima', 'America/Panama', 'America/Rio_Branco', 'Etc/GMT+5']),
('Eastern Standard Time (Mexico)', 'EST', -5, false, '(UTC-05:00) Chetumal', ARRAY['America/Cancun']),
('Eastern Standard Time', 'EST', -5, false, '(UTC-05:00) Eastern Time (US & Canada)', ARRAY['America/Detroit', 'America/Havana', 'America/Iqaluit', 'America/New_York', 'America/Thunder_Bay', 'America/Toronto']),
('Haiti Standard Time', 'HST', -5, false, '(UTC-05:00) Haiti', ARRAY['America/Port-au-Prince']),
('Cuba Standard Time', 'CST', -5, false, '(UTC-05:00) Havana', ARRAY['America/Havana']),
('US Eastern Standard Time', 'EST', -5, false, '(UTC-05:00) Indiana (East)', ARRAY['America/Indiana/Indianapolis', 'America/Indiana/Knox', 'America/Indiana/Marengo', 'America/Indiana/Petersburg', 'America/Indiana/Tell_City', 'America/Indiana/Vevay', 'America/Indiana/Vincennes', 'America/Indiana/Winamac', 'America/Kentucky/Louisville', 'America/Kentucky/Monticello']),
('Turks And Caicos Standard Time', 'TCST', -5, false, '(UTC-05:00) Turks and Caicos', ARRAY['America/Grand_Turk']),
('Paraguay Standard Time', 'PST', -4, false, '(UTC-04:00) Asuncion', ARRAY['America/Asuncion']),
('Atlantic Standard Time', 'AST', -4, false, '(UTC-04:00) Atlantic Time (Canada)', ARRAY['America/Halifax', 'America/Moncton', 'America/Thule', 'Atlantic/Bermuda']),
('Venezuela Standard Time', 'VST', -4, false, '(UTC-04:00) Caracas', ARRAY['America/Caracas']),
('Central Brazilian Standard Time', 'CBST', -4, false, '(UTC-04:00) Cuiaba', ARRAY['America/Campo_Grande', 'America/Cuiaba']),
('SA Western Standard Time', 'SWST', -4, false, '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan', ARRAY['America/Anguilla', 'America/Antigua', 'America/Aruba', 'America/Barbados', 'America/Blanc-Sablon', 'America/Boa_Vista', 'America/Curacao', 'America/Dominica', 'America/Grand_Turk', 'America/Grenada', 'America/Guadeloupe', 'America/Guyana', 'America/Kralendijk', 'America/La_Paz', 'America/Lower_Princes', 'America/Manaus', 'America/Marigot', 'America/Martinique', 'America/Montserrat', 'America/Port_of_Spain', 'America/Porto_Velho', 'America/Puerto_Rico', 'America/Santo_Domingo', 'America/St_Barthelemy', 'America/St_Kitts', 'America/St_Lucia', 'America/St_Martin', 'America/St_Thomas', 'America/St_Vincent', 'America/Tortola', 'Etc/GMT+4']),
('Pacific SA Standard Time', 'PSST', -4, false, '(UTC-04:00) Santiago', ARRAY['America/Santiago']),
('Newfoundland Standard Time', 'NST', -3.5, false, '(UTC-03:30) Newfoundland', ARRAY['America/St_Johns']),
('Tocantins Standard Time', 'TST', -3, false, '(UTC-03:00) Araguaina', ARRAY['America/Araguaina']),
('E. South America Standard Time', 'ESAST', -3, false, '(UTC-03:00) Brasilia', ARRAY['America/Sao_Paulo']),
('SA Eastern Standard Time', 'SEST', -3, false, '(UTC-03:00) Cayenne, Fortaleza', ARRAY['America/Belem', 'America/Cayenne', 'America/Fortaleza', 'America/Maceio', 'America/Paramaribo', 'America/Recife', 'America/Santarem', 'Etc/GMT+3']),
('Argentina Standard Time', 'AST', -3, false, '(UTC-03:00) City of Buenos Aires', ARRAY['America/Buenos_Aires', 'America/Argentina/La_Rioja', 'America/Argentina/Rio_Gallegos', 'America/Argentina/Salta', 'America/Argentina/San_Juan', 'America/Argentina/San_Luis', 'America/Argentina/Tucuman', 'America/Argentina/Ushuaia', 'America/Catamarca', 'America/Cordoba', 'America/Jujuy', 'America/Mendoza']),
('Greenland Standard Time', 'GST', -3, false, '(UTC-03:00) Greenland', ARRAY['America/Godthab']),
('Montevideo Standard Time', 'MST', -3, false, '(UTC-03:00) Montevideo', ARRAY['America/Montevideo']),
('Magallanes Standard Time', 'MST', -3, false, '(UTC-03:00) Punta Arenas', ARRAY['America/Punta_Arenas']),
('Saint Pierre Standard Time', 'SPST', -3, false, '(UTC-03:00) Saint Pierre and Miquelon', ARRAY['America/Miquelon']),
('Bahia Standard Time', 'BST', -3, false, '(UTC-03:00) Salvador', ARRAY['America/Bahia']),
('UTC-02', 'U', -2, false, '(UTC-02:00) Coordinated Universal Time-02', ARRAY['Etc/GMT+2']),
('Mid-Atlantic Standard Time', 'MAST', -2, false, '(UTC-02:00) Mid-Atlantic - Old', ARRAY[]::text[]),
('Azores Standard Time', 'AST', -1, false, '(UTC-01:00) Azores', ARRAY['Atlantic/Azores', 'America/Scoresbysund']),
('Cape Verde Standard Time', 'CVST', -1, false, '(UTC-01:00) Cabo Verde Is.', ARRAY['Atlantic/Cape_Verde', 'Etc/GMT+1']),
('UTC', 'UTC', 0, false, '(UTC) Coordinated Universal Time', ARRAY['America/Danmarkshavn', 'Etc/GMT']),
('Morocco Standard Time', 'MST', 1, false, '(UTC+01:00) Casablanca', ARRAY['Africa/Casablanca', 'Africa/El_Aaiun']),
('GMT Standard Time', 'GMT', 0, false, '(UTC+00:00) Dublin, Edinburgh, Lisbon, London', ARRAY['Europe/Isle_of_Man', 'Europe/Guernsey', 'Europe/Jersey', 'Europe/London']),
('Greenwich Standard Time', 'GST', 0, false, '(UTC+00:00) Monrovia, Reykjavik', ARRAY['Africa/Abidjan', 'Africa/Accra', 'Africa/Bamako', 'Africa/Banjul', 'Africa/Bissau', 'Africa/Conakry', 'Africa/Dakar', 'Africa/Freetown', 'Africa/Lome', 'Africa/Monrovia', 'Africa/Nouakchott', 'Africa/Ouagadougou', 'Africa/Sao_Tome', 'Atlantic/Reykjavik', 'Atlantic/St_Helena']),
('Sao Tome Standard Time', 'STST', 0, false, '(UTC+00:00) Sao Tome', ARRAY['Africa/Sao_Tome']),
('W. Europe Standard Time', 'WEST', 1, false, '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna', ARRAY['Europe/Andorra', 'Europe/Berlin', 'Europe/Busingen', 'Europe/Gibraltar', 'Europe/Luxembourg', 'Europe/Malta', 'Europe/Monaco', 'Europe/Rome', 'Europe/San_Marino', 'Europe/Stockholm', 'Europe/Vaduz', 'Europe/Vatican', 'Europe/Vienna', 'Europe/Zurich']),
('Central Europe Standard Time', 'CEST', 1, false, '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague', ARRAY['Europe/Belgrade', 'Europe/Bratislava', 'Europe/Budapest', 'Europe/Ljubljana', 'Europe/Podgorica', 'Europe/Prague', 'Europe/Tirane']),
('Romance Standard Time', 'RST', 1, false, '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris', ARRAY['Europe/Brussels', 'Europe/Copenhagen', 'Europe/Madrid', 'Europe/Paris']),
('Central European Standard Time', 'CEST', 1, false, '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb', ARRAY['Europe/Sarajevo', 'Europe/Skopje', 'Europe/Warsaw', 'Europe/Zagreb']),
('W. Central Africa Standard Time', 'WCAST', 1, false, '(UTC+01:00) West Central Africa', ARRAY['Africa/Algiers', 'Africa/Bangui', 'Africa/Brazzaville', 'Africa/Douala', 'Africa/Kinshasa', 'Africa/Lagos', 'Africa/Libreville', 'Africa/Luanda', 'Africa/Malabo', 'Africa/Ndjamena', 'Africa/Niamey', 'Africa/Porto-Novo', 'Africa/Tunis', 'Etc/GMT-1']),
('Jordan Standard Time', 'JST', 2, false, '(UTC+02:00) Amman', ARRAY['Asia/Amman']),
('GTB Standard Time', 'GTBST', 2, false, '(UTC+02:00) Athens, Bucharest', ARRAY['Europe/Bucharest', 'Europe/Athens']),
('Middle East Standard Time', 'MEST', 2, false, '(UTC+02:00) Beirut', ARRAY['Asia/Beirut']),
('Egypt Standard Time', 'EST', 2, false, '(UTC+02:00) Cairo', ARRAY['Africa/Cairo']),
('E. Europe Standard Time', 'EEST', 2, false, '(UTC+02:00) Chisinau', ARRAY['Europe/Chisinau']),
('Syria Standard Time', 'SST', 2, false, '(UTC+02:00) Damascus', ARRAY['Asia/Damascus']),
('West Bank Standard Time', 'WBST', 2, false, '(UTC+02:00) Gaza, Hebron', ARRAY['Asia/Gaza', 'Asia/Hebron']),
('South Africa Standard Time', 'SAST', 2, false, '(UTC+02:00) Harare, Pretoria', ARRAY['Africa/Blantyre', 'Africa/Bujumbura', 'Africa/Gaborone', 'Africa/Harare', 'Africa/Johannesburg', 'Africa/Khartoum', 'Africa/Kigali', 'Africa/Lubumbashi', 'Africa/Lusaka', 'Africa/Maputo', 'Africa/Maseru', 'Africa/Mbabane', 'Etc/GMT-2']),
('FLE Standard Time', 'FLEST', 2, false, '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius', ARRAY['Europe/Helsinki', 'Europe/Kiev', 'Europe/Mariehamn', 'Europe/Riga', 'Europe/Sofia', 'Europe/Tallinn', 'Europe/Vilnius']),
('Israel Standard Time', 'IST', 2, false, '(UTC+02:00) Jerusalem', ARRAY['Asia/Jerusalem']),
('Kaliningrad Standard Time', 'KST', 2, false, '(UTC+02:00) Kaliningrad', ARRAY['Europe/Kaliningrad']),
('Sudan Standard Time', 'SST', 2, false, '(UTC+02:00) Khartoum', ARRAY['Africa/Khartoum']),
('Libya Standard Time', 'LST', 2, false, '(UTC+02:00) Tripoli', ARRAY['Africa/Tripoli']),
('Namibia Standard Time', 'NST', 2, false, '(UTC+02:00) Windhoek', ARRAY['Africa/Windhoek']),
('Arabic Standard Time', 'AST', 3, false, '(UTC+03:00) Baghdad', ARRAY['Asia/Baghdad']),
('Turkey Standard Time', 'TST', 3, false, '(UTC+03:00) Istanbul', ARRAY['Europe/Istanbul']),
('Arab Standard Time', 'AST', 3, false, '(UTC+03:00) Kuwait, Riyadh', ARRAY['Asia/Aden', 'Asia/Bahrain', 'Asia/Kuwait', 'Asia/Qatar', 'Asia/Riyadh', 'Etc/GMT-3']),
('Belarus Standard Time', 'BST', 3, false, '(UTC+03:00) Minsk', ARRAY['Europe/Minsk']),
('Russian Standard Time', 'RST', 3, false, '(UTC+03:00) Moscow, St. Petersburg', ARRAY['Europe/Kirov', 'Europe/Moscow', 'Europe/Simferopol', 'Europe/Volgograd']),
('E. Africa Standard Time', 'EAST', 3, false, '(UTC+03:00) Nairobi', ARRAY['Africa/Addis_Ababa', 'Africa/Asmera', 'Africa/Dar_es_Salaam', 'Africa/Djibouti', 'Africa/Juba', 'Africa/Kampala', 'Africa/Mogadishu', 'Africa/Nairobi', 'Antarctica/Syowa', 'Etc/GMT-3', 'Indian/Antananarivo', 'Indian/Comoro', 'Indian/Mayotte']),
('Volgograd Standard Time', 'VST', 4, false, '(UTC+04:00) Volgograd', ARRAY['Europe/Volgograd']),
('Iran Standard Time', 'IST', 3.5, false, '(UTC+03:30) Tehran', ARRAY['Asia/Tehran']),
('Arabian Standard Time', 'AST', 4, false, '(UTC+04:00) Abu Dhabi, Muscat', ARRAY['Asia/Dubai', 'Asia/Muscat', 'Etc/GMT-4']),
('Astrakhan Standard Time', 'AST', 4, false, '(UTC+04:00) Astrakhan, Ulyanovsk', ARRAY['Europe/Astrakhan', 'Europe/Ulyanovsk']),
('Azerbaijan Standard Time', 'AST', 4, false, '(UTC+04:00) Baku', ARRAY['Asia/Baku']),
('Russia Time Zone 3', 'RTZ3', 4, false, '(UTC+04:00) Izhevsk, Samara', ARRAY['Europe/Samara']),
('Mauritius Standard Time', 'MST', 4, false, '(UTC+04:00) Port Louis', ARRAY['Indian/Mauritius', 'Indian/Reunion', 'Indian/Mahe']),
('Saratov Standard Time', 'SST', 4, false, '(UTC+04:00) Saratov', ARRAY['Europe/Saratov']),
('Georgian Standard Time', 'GST', 4, false, '(UTC+04:00) Tbilisi', ARRAY['Asia/Tbilisi']),
('Caucasus Standard Time', 'CST', 4, false, '(UTC+04:00) Yerevan', ARRAY['Asia/Yerevan']),
('Afghanistan Standard Time', 'AST', 4.5, false, '(UTC+04:30) Kabul', ARRAY['Asia/Kabul']),
('West Asia Standard Time', 'WAST', 5, false, '(UTC+05:00) Ashgabat, Tashkent', ARRAY['Antarctica/Mawson', 'Asia/Aqtau', 'Asia/Aqtobe', 'Asia/Ashgabat', 'Asia/Dushanbe', 'Asia/Oral', 'Asia/Samarkand', 'Asia/Tashkent', 'Etc/GMT-5', 'Indian/Kerguelen', 'Indian/Maldives']),
('Yekaterinburg Standard Time', 'YST', 5, false, '(UTC+05:00) Ekaterinburg', ARRAY['Asia/Yekaterinburg']),
('Pakistan Standard Time', 'PST', 5, false, '(UTC+05:00) Islamabad, Karachi', ARRAY['Asia/Karachi']),
('Qyzylorda Standard Time', 'QST', 5, false, '(UTC+05:00) Qyzylorda', ARRAY['Asia/Qyzylorda']),
('India Standard Time', 'IST', 5.5, false, '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi', ARRAY['Asia/Calcutta']),
('Sri Lanka Standard Time', 'SLST', 5.5, false, '(UTC+05:30) Sri Jayawardenepura', ARRAY['Asia/Colombo']),
('Nepal Standard Time', 'NST', 5.75, false, '(UTC+05:45) Kathmandu', ARRAY['Asia/Katmandu']),
('Central Asia Standard Time', 'CAST', 6, false, '(UTC+06:00) Astana', ARRAY['Antarctica/Vostok', 'Asia/Almaty', 'Asia/Bishkek', 'Asia/Qostanay', 'Asia/Urumqi', 'Etc/GMT-6', 'Indian/Chagos']),
('Bangladesh Standard Time', 'BST', 6, false, '(UTC+06:00) Dhaka', ARRAY['Asia/Dhaka', 'Asia/Thimphu']),
('Omsk Standard Time', 'OST', 6, false, '(UTC+06:00) Omsk', ARRAY['Asia/Omsk']),
('Myanmar Standard Time', 'MST', 6.5, false, '(UTC+06:30) Yangon (Rangoon)', ARRAY['Asia/Rangoon', 'Indian/Cocos']),
('SE Asia Standard Time', 'SEAST', 7, false, '(UTC+07:00) Bangkok, Hanoi, Jakarta', ARRAY['Antarctica/Davis', 'Asia/Bangkok', 'Asia/Hovd', 'Asia/Jakarta', 'Asia/Phnom_Penh', 'Asia/Pontianak', 'Asia/Saigon', 'Asia/Vientiane', 'Etc/GMT-7', 'Indian/Christmas']),
('Altai Standard Time', 'AST', 7, false, '(UTC+07:00) Barnaul, Gorno-Altaysk', ARRAY['Asia/Barnaul']),
('W. Mongolia Standard Time', 'WMST', 7, false, '(UTC+07:00) Hovd', ARRAY['Asia/Hovd']),
('North Asia Standard Time', 'NAST', 7, false, '(UTC+07:00) Krasnoyarsk', ARRAY['Asia/Krasnoyarsk', 'Asia/Novokuznetsk']),
('N. Central Asia Standard Time', 'NCAST', 7, false, '(UTC+07:00) Novosibirsk', ARRAY['Asia/Novosibirsk']),
('Tomsk Standard Time', 'TST', 7, false, '(UTC+07:00) Tomsk', ARRAY['Asia/Tomsk']),
('China Standard Time', 'CST', 8, false, '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi', ARRAY['Asia/Hong_Kong', 'Asia/Macau', 'Asia/Shanghai']),
('North Asia East Standard Time', 'NAEST', 8, false, '(UTC+08:00) Irkutsk', ARRAY['Asia/Irkutsk']),
('Singapore Standard Time', 'SST', 8, false, '(UTC+08:00) Kuala Lumpur, Singapore', ARRAY['Asia/Brunei', 'Asia/Kuala_Lumpur', 'Asia/Kuching', 'Asia/Makassar', 'Asia/Manila', 'Asia/Singapore', 'Etc/GMT-8']),
('W. Australia Standard Time', 'WAST', 8, false, '(UTC+08:00) Perth', ARRAY['Antarctica/Casey', 'Australia/Perth']),
('Taipei Standard Time', 'TST', 8, false, '(UTC+08:00) Taipei', ARRAY['Asia/Taipei']),
('Ulaanbaatar Standard Time', 'UST', 8, false, '(UTC+08:00) Ulaanbaatar', ARRAY['Asia/Choibalsan', 'Asia/Ulaanbaatar']),
('Aus Central W. Standard Time', 'ACWST', 8.75, false, '(UTC+08:45) Eucla', ARRAY['Australia/Eucla']),
('Transbaikal Standard Time', 'TST', 9, false, '(UTC+09:00) Chita', ARRAY['Asia/Chita']),
('Tokyo Standard Time', 'TST', 9, false, '(UTC+09:00) Osaka, Sapporo, Tokyo', ARRAY['Asia/Dili', 'Asia/Jayapura', 'Asia/Tokyo', 'Etc/GMT-9', 'Pacific/Palau']),
('North Korea Standard Time', 'NKST', 9, false, '(UTC+09:00) Pyongyang', ARRAY['Asia/Pyongyang']),
('Korea Standard Time', 'KST', 9, false, '(UTC+09:00) Seoul', ARRAY['Asia/Seoul']),
('Yakutsk Standard Time', 'YST', 9, false, '(UTC+09:00) Yakutsk', ARRAY['Asia/Khandyga', 'Asia/Yakutsk']),
('Cen. Australia Standard Time', 'CAST', 9.5, false, '(UTC+09:30) Adelaide', ARRAY['Australia/Adelaide', 'Australia/Broken_Hill']),
('AUS Central Standard Time', 'ACST', 9.5, false, '(UTC+09:30) Darwin', ARRAY['Australia/Darwin']),
('E. Australia Standard Time', 'EAST', 10, false, '(UTC+10:00) Brisbane', ARRAY['Australia/Brisbane', 'Australia/Lindeman']),
('AUS Eastern Standard Time', 'AEST', 10, false, '(UTC+10:00) Canberra, Melbourne, Sydney', ARRAY['Australia/Melbourne', 'Australia/Sydney']),
('West Pacific Standard Time', 'WPST', 10, false, '(UTC+10:00) Guam, Port Moresby', ARRAY['Antarctica/DumontDUrville', 'Etc/GMT-10', 'Pacific/Guam', 'Pacific/Port_Moresby', 'Pacific/Saipan', 'Pacific/Truk']),
('Tasmania Standard Time', 'TST', 10, false, '(UTC+10:00) Hobart', ARRAY['Australia/Currie', 'Australia/Hobart']),
('Vladivostok Standard Time', 'VST', 10, false, '(UTC+10:00) Vladivostok', ARRAY['Asia/Ust-Nera', 'Asia/Vladivostok']),
('Lord Howe Standard Time', 'LHST', 10.5, false, '(UTC+10:30) Lord Howe Island', ARRAY['Australia/Lord_Howe']),
('Bougainville Standard Time', 'BST', 11, false, '(UTC+11:00) Bougainville Island', ARRAY['Pacific/Bougainville']),
('Russia Time Zone 10', 'RTZ10', 11, false, '(UTC+11:00) Chokurdakh', ARRAY['Asia/Srednekolymsk']),
('Magadan Standard Time', 'MST', 11, false, '(UTC+11:00) Magadan', ARRAY['Asia/Magadan']),
('Norfolk Standard Time', 'NST', 11, false, '(UTC+11:00) Norfolk Island', ARRAY['Pacific/Norfolk']),
('Sakhalin Standard Time', 'SST', 11, false, '(UTC+11:00) Sakhalin', ARRAY['Asia/Sakhalin']),
('Central Pacific Standard Time', 'CPST', 11, false, '(UTC+11:00) Solomon Is., New Caledonia', ARRAY['Antarctica/Macquarie', 'Etc/GMT-11', 'Pacific/Efate', 'Pacific/Guadalcanal', 'Pacific/Kosrae', 'Pacific/Noumea', 'Pacific/Ponape']),
('Russia Time Zone 11', 'RTZ11', 12, false, '(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky', ARRAY['Asia/Anadyr', 'Asia/Kamchatka']),
('New Zealand Standard Time', 'NZST', 12, false, '(UTC+12:00) Auckland, Wellington', ARRAY['Antarctica/McMurdo', 'Pacific/Auckland']),
('UTC+12', 'U', 12, false, '(UTC+12:00) Coordinated Universal Time+12', ARRAY['Etc/GMT-12', 'Pacific/Funafuti', 'Pacific/Kwajalein', 'Pacific/Majuro', 'Pacific/Nauru', 'Pacific/Tarawa', 'Pacific/Wake', 'Pacific/Wallis']),
('Fiji Standard Time', 'FST', 12, false, '(UTC+12:00) Fiji', ARRAY['Pacific/Fiji']),
('Kamchatka Standard Time', 'KST', 12, false, '(UTC+12:00) Petropavlovsk-Kamchatsky - Old', ARRAY['Asia/Kamchatka']),
('Chatham Islands Standard Time', 'CIST', 12.75, false, '(UTC+12:45) Chatham Islands', ARRAY['Pacific/Chatham']),
('UTC+13', 'U', 13, false, '(UTC+13:00) Coordinated Universal Time+13', ARRAY['Etc/GMT-13', 'Pacific/Enderbury']),
('Tonga Standard Time', 'TST', 13, false, '(UTC+13:00) Nuku''alofa', ARRAY['Etc/GMT-13', 'Pacific/Fakaofo', 'Pacific/Tongatapu']),
('Samoa Standard Time', 'SST', 13, false, '(UTC+13:00) Samoa', ARRAY['Pacific/Apia']),
('Line Islands Standard Time', 'LIST', 14, false, '(UTC+14:00) Kiritimati Island', ARRAY['Etc/GMT-14', 'Pacific/Kiritimati']);

-- Enable RLS on timezones table (reference data should be publicly readable)
ALTER TABLE timezones ENABLE ROW LEVEL SECURITY;

-- Create policy to allow everyone to read timezones (reference data)
CREATE POLICY "Timezones are publicly readable" 
  ON timezones 
  FOR SELECT 
  TO public
  USING (true);

-- Create trigger to update updated_at timestamp
CREATE TRIGGER timezones_updated_at
  BEFORE UPDATE ON timezones
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
