
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtyugokvlksnatftpucm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0eXVnb2t2bGtzbmF0ZnRwdWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4Njg3NzUsImV4cCI6MjA2MzQ0NDc3NX0.7AZFW9BsEeUatjnJDAfnvrOBd_XMq1Ia_iWAKLzGAw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage,
    detectSessionInUrl: true,
    flowType: 'pkce',
    redirectTo: 'https://talentflow-dashboard-v3-95.lovable.app'
  }
});
